# Generated by Django 2.2.2 on 2019-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField(max_length=10000)),
                ('total_cost', models.DecimalField(decimal_places=3, max_digits=9)),
                ('status', models.CharField(choices=[('P', 'Payed'), ('N', 'Not Payed')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('CU', 'Custom'), ('ST', 'Standard'), ('RE', 'recommendation')], max_length=20),
        ),
    ]
