# Generated by Django 2.2.2 on 2019-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20190605_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='', height_field=500, upload_to='media/subCategory/', width_field=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(height_field=500, upload_to='media/category/', width_field=500),
        ),
    ]
