# Generated by Django 2.2.2 on 2019-06-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20190607_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='customCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوانش چی باشه', max_length=20)),
                ('image', models.ImageField(help_text='تصویرش چی باشه', upload_to='subCategory/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', help_text='توضیحات مربوط به دسته بندی رو اینجا بنویس. یچیزی که مشتری رو جذب کنه', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='تصویرش چی باشه', upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='عنوانش چی باشه', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('CU', 'Custom'), ('ST', 'Standard')], help_text='نوعش چی باشه. ساختی باشه یا نه', max_length=20),
        ),
        migrations.DeleteModel(
            name='subCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='mainApp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub',
            field=models.ForeignKey(blank=True, help_text='اگر ساختنی هست این قسمت رو انتخاب کن وگرنه خالی بزارش', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='mainApp.customCategory'),
        ),
        migrations.AddField(
            model_name='customcategory',
            name='category',
            field=models.ForeignKey(help_text='این تو کدوم دسته بندی قرار میگیره', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='mainApp.category'),
        ),
    ]
