# Generated by Django 2.2.2 on 2019-06-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20190608_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub',
            field=models.ForeignKey(blank=True, help_text='اگر ساختنی هست این قسمت رو انتخاب کن وگرنه خالی بزارش', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='mainApp.customCategory'),
        ),
    ]
